import type { PriceObservationProvider } from './price-observation-provider';
import type {
  AssetValuationDto,
  PortfolioValuationSummaryDto,
  PriceObservationDto,
  ValuationStatus,
} from './valuation-types';

function deriveValuationFromObservation(quantity: string, observation: PriceObservationDto): AssetValuationDto {
  const base = {
    assetId: observation.assetId,
    chainId: observation.chainId,
    symbol: observation.symbol,
    quantity,
    confidence: observation.confidence,
    observation,
    provenance: observation.provenance,
  };

  if (observation.status === 'available' && observation.priceUsd !== null) {
    return {
      ...base,
      status: 'available',
      valueUsd: Number(quantity) * observation.priceUsd,
      warnings: [...observation.warnings],
    };
  }

  const statusMap: Record<PriceObservationDto['status'], ValuationStatus> = {
    available: 'available',
    stale: 'stale',
    unavailable: 'unavailable',
    low_confidence: 'low_confidence',
  };

  return {
    ...base,
    status: statusMap[observation.status],
    valueUsd: null,
    warnings: [...observation.warnings],
  };
}

export function summarizeValuations(valuations: AssetValuationDto[]): PortfolioValuationSummaryDto {
  const valued = valuations.filter(v => v.status === 'available');
  const stale = valuations.filter(v => v.status === 'stale');
  const unavailable = valuations.filter(v => v.status === 'unavailable');
  const lowConfidence = valuations.filter(v => v.status === 'low_confidence');

  return {
    status: unavailable.length === valuations.length ? 'unavailable' : unavailable.length > 0 ? 'partial' : 'available',
    totalValueUsd: valued.reduce((sum, item) => sum + (item.valueUsd ?? 0), 0),
    valuedAssetCount: valued.length,
    staleAssetCount: stale.length,
    unavailableAssetCount: unavailable.length,
    lowConfidenceAssetCount: lowConfidence.length,
    warnings: valuations.flatMap(item => item.warnings),
  };
}

export class PlaceholderValuationService {
  constructor(private readonly provider: PriceObservationProvider) {}

  async valueAssets(inputs: Array<{ assetId: string; quantity: string }>): Promise<AssetValuationDto[]> {
    const observations = await this.provider.getBatchPriceObservations(inputs.map(input => input.assetId));

    return inputs.map((input) => {
      const observation = observations.find(item => item.assetId === input.assetId);
      if (!observation) {
        return deriveValuationFromObservation(input.quantity, {
          assetId: input.assetId,
          chainId: 369,
          symbol: 'UNKNOWN',
          source: 'placeholder',
          observedAt: new Date(0).toISOString(),
          priceUsd: null,
          confidence: null,
          staleAfter: new Date(0).toISOString(),
          status: 'unavailable',
          warnings: ['No observation returned for requested assetId.'],
          provenance: {
            provider: 'placeholder',
            providerAssetId: input.assetId,
            retrievalMethod: 'placeholder',
            notes: ['Deterministic fallback generated by backend placeholder valuation service.'],
          },
        });
      }
      return deriveValuationFromObservation(input.quantity, observation);
    });
  }
}
